export const users = [
  {
    id: _1,
    name: "kumar",
    mobile_number: "076564763",
    profile_pic: "https://source.unsplash.com/random/200x200",
    vehicles: [],
  },
  {
    id: _2,
    name: "shimak",
    mobile_number: "0764564763",
    profile_pic: "https://source.unsplash.com/random/200x200",
    vehicles: [],
  },
  {
    id: _3,
    name: "honda",
    mobile_number: "076564563",
    profile_pic: "https://source.unsplash.com/random/200x200",
    vehicles: [],
  },
  {
    id: _4,
    name: "sirisena",
    mobile_number: "075664763",
    profile_pic: "https://source.unsplash.com/random/200x200",
    vehicles: [],
  },
  {
    id: _5,
    name: "juzail",
    mobile_number: "076566663",
    profile_pic: "https://source.unsplash.com/random/200x200",
    vehicles: [],
  },
];

export const vehicles = [
  {
    owner_id: 2,
    img: "https://source.unsplash.com/random/200x200",
    price: "negotiable",
    city: "colombo",
    area: "Maradhana",
    category: "Motor-cycle",
    Brand: "",
    Model: "",
    Transmission: "",
    Year: "",
    Fuel: "",
    Enginecc: "",
    Milage: "",
    Document: "",
    Additional_description: "",
  },
  {
    owner_id: 2,
    img: "https://source.unsplash.com/random/200x200",
    price: "negotiable",
    city: "colombo",
    area: "Maradhana",
    category: "Motor-cycle",
    Brand: "",
    Model: "",
    Transmission: "",
    Year: "",
    Fuel: "",
    Enginecc: "",
    Milage: "",
    Document: "",
    Additional_description: "",
  },
  {
    owner_id: 2,
    img: "https://source.unsplash.com/random/200x200",
    price: "negotiable",
    city: "colombo",
    area: "Maradhana",
    category: "car",
    Brand: "",
    Model: "",
    Transmission: "",
    Year: "",
    Fuel: "",
    Enginecc: "",
    Milage: "",
    Document: "",
    Additional_description: "",
  },
  {
    owner_id: 3,
    img: "https://source.unsplash.com/random/200x200",
    price: "negotiable",
    city: "colombo",
    area: "Maradhana",
    category: "three-wheel",
    Brand: "",
    Model: "",
    Transmission: "",
    Year: "",
    Fuel: "",
    Enginecc: "",
    Milage: "",
    Document: "",
    Additional_description: "",
  },
];
